sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t chabilkansal/docker-react .

script:
  - docker run -e CI=true chabilkansal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-south-1-431029909730"
  bucket_path: "docker-react"
  on: 
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"